import {DynamicFieldModel, FormTypes} from "./types";

export const MockDynamicData: DynamicFieldModel[] = [
	{
		key: "first_name",
		name: "first_name",
		type: FormTypes.text,
		label: "First name",
		options: [],
		required: true,
		maximum: "20",
		minimum: "5",
		placeholder: "Enter your first name",
		default_value: "",
	},
	{
    key: "last_name",
		name: "last_name",
		type: FormTypes.text,
		label: "Last name",
		options: [],
		required: true,
		maximum: "20",
		minimum: "5",
		placeholder: "Enter your last name",
		default_value: "",
	},
	{
		key: "age",
		name: "age",
		type: FormTypes.number,
		label: "Age",
		options: [],
		required: false,
		maximum: "60",
		minimum: "18",
		placeholder: "Enter your age",
		default_value: "",
	},
	{
		key: "user_email",
		name: "user_email",
		type: FormTypes.email,
		label: "User' Email",
		options: [],
		required: true,
		maximum: "0",
		minimum: "1",
		placeholder: "Enter your email Address",
		default_value: "",
	},
	{
		key: "date_of_birth",
		name: "date_of_birth",
		type: FormTypes.date,
		label: "Date of Birth",
		options: [],
		required: true,
		maximum: "2020-05-01T20:29:56.421Z",
		minimum: "1990-10-25T20:29:56.421Z",
		placeholder: "Enter your date of birth",
		default_value: "2020-10-20T20:29:56.421Z",
	},
]